//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.06 at 10:17:33 PM SAST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.mtech.mts/soapservice/soap/country", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package mts.mtech.soapservice.soap.country;
